name: matrix
on: [push, workflow_dispatch]

jobs:
    build:
        
        strategy:
            max-parallel: 2
            matrix: 
                version: ['18', '20', '4']
                os: ['ubuntu-latest', 'windows-latest']
        runs-on: ${{ matrix.os }}
        steps:
        - name: test
          run: date

        - name: install nodejs
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.version }}

        - name: checkout
          uses: actions/checkout@v4

        - name: docu
          run: npm install docusaurus

        - name: ls
          run: ls