name: matrix
on: [push, workflow_dispatch]

jobs:
    build:
        strategy:
            max-parallel: 2
            matrix: 
                version: [3.11, 3.12]
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
        - name: test
          run: date

        - name: install python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.version }}

        - name: checkout
          uses: actions/checkout@v4

        - name: docu
          run: pip install mkdocs

        - name: ls
          run: ls